export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
export const HIDE_CONNECTIONS = 'HIDE_CONNECTIONS';

export const UPDATE_INPUT = 'UPDATE_INPUT';

// MRP Actions
export const ADD_MATERIAL = 'ADD_MATERIAL';
export const UPDATE_MATERIAL = 'UPDATE_MATERIAL';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
export const SET_MATERIALS = 'SET_MATERIALS';

export const ADD_INVENTORY_TRANSACTION = 'ADD_INVENTORY_TRANSACTION';
export const SET_INVENTORY = 'SET_INVENTORY';

export const ADD_BOM_ITEM = 'ADD_BOM_ITEM';
export const REMOVE_BOM_ITEM = 'REMOVE_BOM_ITEM';
export const SET_BOM = 'SET_BOM';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
